services:
  web:
    container_name: welearn-api
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.14}
    command: uvicorn src.main:app --host 0.0.0.0
    network_mode: host
    volumes:
      - .:/app
    ports:
      - 8000:8000
    profiles: [prod]
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.4
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 8080:8080
    profiles: [dev]
