config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:CVS807YirBrmwzZPg7ZusmuQlRk2Z5fA7q0FL6or748=,iv:dcakolSW8odoMR9rZJQeRoSdfpTfVNMjs9ErldLk4ec=,tag:ycKc15UcW7MtsARklJk+Uw==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:gvtwPHReMmaaKcNWUcf63NO6GpAiiyLRimQkuJC1qKlSa/leVe5oLJzY9/3JkY4S9LJvs7JI2MT2AvUgMRd+qPfMHySgosOQPxx0PJAtp6ikfAKb,iv:t9Pb1+XKP5B2VwA9c9fguR/oULpIETFngt0cmqJPb7I=,tag:ABBYMiyjUW/dsUESQB1Uqg==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:ceGyPsjjZ09T3U+zAJdTaqYr3ly5/wW4GYtJxd0noTI=,iv:1chC8dCnBhtqCd8Ex34dlSAO3LT+9IlbI5SQXdXt79U=,tag:2qd1zxwpDnKwFcGVZE8siw==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:T+LaC4wkSed2ZbuZZA9EnqsZ,iv:7JM9iNYjLQ63kqZ5AtDODkE0BELWRal3wTB4G8W8Kho=,tag:IRUsvN4EowdEhJsSx++7Mg==,type:str]
        MISTRAL_API_KEY: ENC[AES256_GCM,data:onBQp43O+S55XnaNKX2wZ9SW65owQR2rNost6Mw8/R8=,iv:rL9K7AD/mpl8lgq7XOu0qtfC/zg2x8MrSIKJW1idkNw=,tag:QDqgOruwTtxZH4IVIGtOIg==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:b0QcVmOiCxTrMqxPi+jI/NFOB4Zo6QA=,iv:IO39BNbdBcsLMYX5BydeQWM5oSIGPz66ldYKkGPmy7Q=,tag:UmkHbz1x90RoZ7Nw2gi02A==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:TTK/V7kI3W7UC4P2OoIJiCW+eM78j7+nhPK007sYwlhLRv6Q6dXIYT3jjPyz2r8HJBBnLM5t4leWU+97jDtYYEwIrdGDmEAw8z98vLchU8d+O8Q5CfXlSg==,iv:eETF+0rF/X9GyIGKQujbRM+KeGZvzeCtqYrE7e4VaPQ=,tag:S99K8hY6JEEoPjWMYXINFw==,type:str]
sops:
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRenNBNFRENnR1dWhiZ1Vl
            ZU9kLy9XK2dhTmRlV1hLMzkyaWZPdFQ3akdZCmZyVmNkZWFRa3NlSVF2bGp4MHZW
            UFR0K0h5QWc3N1pWOUxKS08xeGNZSTAKLS0tIDJLTHpDOEV3bVZpaTNFY2tiZHg5
            NlNJVVorOU0wLzJ1UDN5cG1JNFZsdm8KjlgJu3c1xl/yNR9EkCmLZoLbNslrVi0f
            syR6hiU/JJIbAg/mWOslH11lEkY9j3OjXEDpoAJDKbBDP3HgOohgdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYk5KWDBULzhKeWpMSWNF
            TWRVTzJIbkExeSszaXpWZUdBMGwyMlJXS1JnCk96L094SVVYNWdxWmlrMUdwc1ZC
            Z3RqcDlDd2ZHL2gxbDYxczVqYW9qcjQKLS0tIGpWYUloeEh0NTF4MitZcHNlOEZv
            VVlTMXdzeDlDcktOZHhoZkZFVm00V0UKRK15kL6oSezlAo28dKtVBGDFRjVdTh18
            bmhnCIyu/h11rbp2EI+PAXeFWqJeZmmr7E23UUAsCrRr+l6v32U1lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbHdGcmZXc0UxMnlGcUJo
            QVdEc1pFaW1Ka085SDhrQ3draTNaeGt4OWpRCi8veUdpTHdoTkRTZEFPZUt6TDhF
            K0lrREp2N214aUJibGVRbzBzbnlDZkUKLS0tIFlWNHkya0Q5bnpkZlNpOGtydUEx
            RC9oV1pEejBwTEprVXFZZnZkdGphNVUKrYxg7GCXUP+QFP8Lt2AfZL6ykZnxu8gD
            GQBbXipGOJ0dsm662/UShzwncxhliGeiNgB47rtbJPcxEfW5wvl70w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZEY5STZFL0pCVlJYZTUx
            WG5VR2cySG92cG0rL3NYNktaKzVhd3I3WTM4Cm9yaEZtK0dLL0ZrOVhLaGdTc1E2
            aUJ0Smh1R1VyY3QrTDBLZGl0WkJ4SVUKLS0tIGpPek9JcW4waXBkTTR5RC8rMjQz
            Q2Yzd1hKRkJuamtudDA4ellTWlp5eGsKKI6ne7rV2iwRUk9FkO9wXqAUabq/iOjQ
            1S1neB65JSTJOg88Z0+Mwr2qzZsAzIxFxSpoG3JEGB+HKdJEkvSBLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINlJpR0NxWVRsdVRscHAx
            NHNiRmI4N2pxMkVOcmRYNWRzaUFXMWJQMDBvCmMrc2wyWjdobnFXZlY4aFo0Z1Ji
            NjVVRWhYVzM0bFU5RGJsYkJteldiMDAKLS0tIFFoandEczM1SHMvdGs2cENtS09R
            dlJjN2hmVlhXbk9NTHU3cnYwSE1KTU0KqFNsuUdROofa1x6nYL5qXYwVhk5MAr6Q
            4r7wNXdlxi3B3NEHJjTCLQrS5D+iRt/mepar30Yd1Y+r4WIRQh3N9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweGRNaVpCNW10N2s0OGtz
            b0kvbjcxNWZzSEgrQWQ4aCszSnJMK1hxSnhzCmxpRTI5T0hTNmgxSVlCa0pNTUJ4
            Z3FJaWhzc3crK1ZrajB3V0h1NWh2bzgKLS0tIG90a3p1Mm1STDVOZmJ0Vk9NQ3FO
            ODU0QUsyTVNHRkF2YzZSR04xTXNhcW8Kj81WL5iQezjdJKt0UHZZioYVjplo5mXS
            aYMPMfLOlHXtFkpaZizbJJWdS2uQek3pSg69qEdjvyjNjH1ZOLjpxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbHJPcHpQWSsxaGpFSXlR
            dUk4Z2g5QURaYVRKVFhzMVdYTU55LzZjcjFrCkR2Y0ZMTGIraW9wL0Z4S1A1ZkVE
            OHZpU2JOL2N5RHdCYVdnR1U2Z0RJLzgKLS0tIEZpVGRpTGlVcHY2d25HazVhR3BZ
            MjNKM1VmVDBXV25FOEtqWm4va3BoZFkKHRnHTm5h3Hoo5fSNs7CdP5KheWZFuU+G
            NKg/8Vm3qsGyNgV/l33TiaysIz02sro1+ZAuRxnr0STAaNX4Z8fcNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T14:13:13Z"
    mac: ENC[AES256_GCM,data:wi64FB7cDBlS4FWJNkxd+scqswRlBv8zavInSnREoaLRCJ0Mo69n/ge2uB6RNum3qP/VFDrZzLUQ5uFcC1uKlqXUGP78u2srqt3Gljd716xCGI4dPI1sV19CbyMBHEYnYPq1bn/z0J+l+0s4G1+M2Ym9m1m8R0/rlEfIfIbD05E=,iv:Zdjf2CXFo2alz70lnV5GCdM/Uh6SDAqWYh8K1Xu9K6A=,tag:SPWfFeywx7bTWy/FGNgaug==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.4
