config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:vU5sozgleY904OU1Fb0yEaRzWYNHnCD2ILjthvtSfk4=,iv:b7ItArThdtIsz1qvgpptbOq96GHa1q6VWAweHYWw2Po=,tag:emJB+azc6vcIWCgv8idtyg==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:FjMSqC6wQM4/1cg5hwM3qAZiKmDEEU0rz6l44XDr0HQ0WLXRYKxDcm/0Ii1khG693fyQJalH7lvf8CRVdD4mnIm3KOaw5Q5MCkqrqoQo2GGm+7ZF,iv:h157m7hUESIOMC81yrnxzG//fInFLfsR8o2zYTsGcUs=,tag:pMOQn7+ijCbvYh1AksjYbQ==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:GKEHlKS5GgzSO+rHYYvrdL0e7WDZDyByD6mYbDmSNZQ=,iv:k/SHzVKSvMr0ibz3O19yQc3Hz4rzFRALxINlNJRLAwk=,tag:9sgSAnfTKEL5SDPyyw2uhA==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:8GsISVAuJyIh0WUFwb9mpqyWcNT04fnmpH4ru5CA+aw=,iv:oGKLDiadbhRQWVSE5J/4QJbppiTIcHhNr9fFY7XI0jY=,tag:Ksk0uMrB9fmVT8thQODFJA==,type:str]
        MISTRAL_API_KEY: ENC[AES256_GCM,data:2om3jEYb/E8bexmXO1LVWMp5fV4WOm51WCiJLiDEF3g=,iv:aYnBjQt3ZmK0DC4VGcqTGFUYRIOKrewkvoZC2Iz1ArY=,tag:eHpoeTdk5QVaKrqUJYueVw==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:vhsGuyM8IYCRua2BQtuYpLI/Dzdx,iv:kPcuAWarV4RXujfwe+9rKe/YWARoeOcFp789WwrI+z8=,tag:Hg8JJmYW0Zuz/2brM/z8yQ==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:xssnW7Kk3LGmF9dpeCiiV2Z7vyNo4n0aSMcA3aXJYd7uvx7B1HmmSRnc47y3pBS8Hg0dc+6Lf0AIod/Yr2mMC+Dfoosfj2oiY4P/7FQZNMD2xVuZCebTYA==,iv:wlEwj0M1U/EIgVbqxiT0aLgtcwmVGfuRgTaOdQYs6IU=,tag:pLiJujwzEMZOg1xEM22Ojg==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYzlZMUY0R2RnZEFGK3hl
            NUhScmFIL0ZrczdZNEs1aE5OVlZ3ZzJlL1VBCk5HdU4vQUtYK1hiVmtvL3JlMmFZ
            Z1RWb0FYc1ZsdWpJUGhRTUhGWFcyU00KLS0tIHJ6M3V6a2dOcFVNSlpMYlZ0V1pL
            dmZiUlJnSHprMUVPT09ja2VMOVdML00KKIm9cvD8QXKi6UPKRthHDjCWbDMmIsAj
            /TahamnxttcrfgqE8D67habSIf9IghNMcFurMwmJJWisqdJ9mlTP+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOXpGNncxM1o4RnRpa3JX
            ZDc3WE8yVkgwMm9HQkg3VXhzSTZZYWo1dmswCnorWnR4M1dOY0VDN1g5NTFNVm00
            RjlubVNBcDRXVGVzMXk1R0dOUE4zMFEKLS0tIFRPMjd0aXNTZUs2ZUFWcVlIMldz
            RzJvRmNPNERtL0pYQ1hyRHA0WXlFb0EKd2e1DjNb6N2ZS50u6hJkm79wsGhzDWhE
            EguDdRO4R4cjLQGhlhc0D9tMx/c+lUxEAkNOJFmf3vRc7gfUFfg5Gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUDBPdWtienhQUG5LZnA0
            TjhqMEZib0FCMkx6WEl3TFdtNHZpZzhLU1NNClFrUng1Y1hBZzA4NGc4eit5OHM2
            dkpGS0g1dG11djF1WmExTHFRZG9XMGsKLS0tIHZlQjhPSTMvWnhjTUtQeWxuNDlu
            RzZKUEJtdlFCOU5aM29jV0Q3bXMxSFUKVGtQfDl6iKEO2rEkPYlXkV5I8YR8t5xi
            UIgqdoMGZvCKTJdyByG5VtQDstVVW5QuKzvE2flvawzFYUkByQ5B/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QjhsVGp5dFIyZU9aODJy
            eHJJdVhuM2VhVkFOZHZ1UkxSdCttWjZZOGcwCjgxN05kUExYK0FHcnE4U21HSi92
            b1lNT2NIQjh1WXY4QUdpV3UvYmMwWkkKLS0tIHNUeHA5Qnk1U2NCeGFkT0ltczRy
            ZllPTE5xa1RDeUd0WmVPczFhZzVxdWsKMsmEsYCBu7q01AUwakRUpPNvkJmlGMZi
            VZyVhAOTq3p6UQ80JDc2MYBbe08LR4bnQo0aXBR9oFHw9JMyaq2ZAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dVJBZTBURHdQTmxTNmZC
            WkZqbGp1YWlyYTNIOW5BNlVGdnlNL0ZVczJrCnF0SVBrSXp5Rnd4VnRydGVrcTd1
            RkJSYldjTldoSDc2L0dPNHRpSkEyWHcKLS0tIHl6WFI4cnVUQlFBWklhVEtRL2Y4
            WTdMOXZ3K1c1eWduNk83YWQ5Nkg1bzQKTvb04Jfk4DZalSl96Jf+Fl1ccQm3FVWi
            LhFnJvUrNI8sY2gkmHxc22H76X8bE2GhDl3TjaJFBOWZmPQlUOsWEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYlNnS2Y5bkExY0ptQXls
            V05BdzBiMTVyZnlvc253ZnhNQXdHSDFqSUdNCm9iNG9DUnpnU3o0WSsyWSs3eUZi
            VUFsZFFJSG9qUWtXQm9XeUZXTXA5UHcKLS0tIHBTNExkclkwMWEweVlJa1VadlBr
            Z08zTlh4VWFwQzB0cnVRVjJ3VU16ZG8K85BIPu9f3U1D9UhcbyZMLhHn7Ea5L6+4
            CEUvSSt5a1EPZDbcd6a+502/ssFD/cuqdrjx0hSfNR56l2BrTYt6ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYjZkVE1XWnBLc2srcmg1
            YTV5SWVpYUJCY3k3QnVuSjMvUGpvb2VQTnljCjNpcnlqbTVPYytUV1N0ZmdmM3dy
            VDRCRGZiakJSVTFWblF5OW9kRjJqbjgKLS0tIGJMWHY4SXF6ZlpwTXdPN21sOWl6
            T0k2ekxSNk9DNFlncGpRR0VmdlFhdWsKnr87J47tm8ksBLFio1frJo8rknlchfdl
            skOOxxXqlhwmNg0TUSZaqtW6qUTZCExt0zN1QFFK5WPxa23m3O1s5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T13:05:26Z"
    mac: ENC[AES256_GCM,data:ZFiWNcr07s7GcnleGpFZWb+YIk1Hv5nut4GFn4o2p5YFd0IvycuFWybk3sw1e4GmPoIJwaXiuSIThUYaZSBbuAzy9u7QZj0tkiVti7otbccsTj+mFOQ4p4iJty1Ms6+S03O4Yd3jWOugJQMbzuMm4OHKkI2rorvaVOdyQjvPK6c=,iv:+WSNB3GrlxU7kOCnAeI1M1JkTQG/ssEXD+QYt2WcwjM=,tag:Gc19gH91iYb6tAj0PKI8Wg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
