config:
    sensitive:
        AZURE_API_KEY: ENC[AES256_GCM,data:2SKfNFOQgFCZIQs5Q8lUSLb3q1hAGsdQ2ZUOZDnz7Zc=,iv:gLCItS1BzCAjw6unQKwlQHasmxLQEWg72iyiBJ1ReVI=,tag:mU0kbbQDNX5b+FjXKOm/qw==,type:str]
        AZURE_MISTRAL_API_KEY: ENC[AES256_GCM,data:UauHNn4plShPncBzt1ISVKZJoFtSi4ZSyVkofTnMCzt8qv8HP8RlRnxrZrc2gqud+kuSamuMt+7fWiT9UY1mSZcjqss0iGcbE3u3nBGGr6BDYAFl,iv:n/QYV3jIfknIo/XQ65KO2Ks/jn2gq2mEziItcRYx08g=,tag:we2Csg2+F6p1v8yA33xooA==,type:str]
        AZURE_APIM_API_KEY: ENC[AES256_GCM,data:FKrJaw42ZBPgJoHvoVLMpt0l/aQKH7ihKYVgeirXLkM=,iv:pRRdDoi1m1uZOrSm1+jRpltwP9bvj1YbID3c3HdcBnI=,tag:0CkVoHcwZKd0JfLxR3Qv3g==,type:str]
        PG_PASSWORD: ENC[AES256_GCM,data:J5w6BskdIVlZ8trAj4q4Wyig6jINo21J8awpwirQAZ4=,iv:+q1S62srni1fuyfQd05GqN3q3wnnnrufLeJGd4lsPXU=,tag:7JnD93zQJppmWXowKAh+5w==,type:str]
azureSecrets:
    azurestorageaccountname: ENC[AES256_GCM,data:xJHag9lIKEfpp7GclGN4QRG9yPxq,iv:fIETSRMpBBboZB+1OvmYE4vvEOnb998639C8OF1C7sE=,tag:YRXWWr3uDo/lv/f3eOT1/Q==,type:str]
    azurestorageaccountkey: ENC[AES256_GCM,data:/E8B8WvdwMdDLaXUoNEvUzPG7qJdFwNv36gmAEnyND6n9Ise3tFhDVD7BE6c85QpanHNJHgVOan8lZiCd/D2tV+BRtgTJnoUaqCoXSyKlIAKlGHpITXsBA==,iv:egR5ipr1u//D0AXAiIXXiF7wx/j2bv5tg/06MaOU/ZI=,tag:VoFBDbUaUkB3017RkeF4gw==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWElGWmdwM1p0V3pVVnZL
            Z2I2WW9LdDBCcXNBb1JjZkR6a2s0YTNOdHlvCnJwMEFnQTROQytWc0dyY0U4dEMv
            MHhJNHozTzAra2JyMmZ4YWd6SzlHMVUKLS0tIEZKT3ZlYkgvSi95NzFSMkE4YVcz
            U3BjOEdnUGlSM3I0ZHNtczFveDNNdVUK1+W0DirLY2rC6J1WJzmKL11paGVdNrFq
            GEVq2JiXz5C+ZzqPmx5ZWIlL82SsxSkSr332gxC7M7FKhUmRTs/xVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcDVBUjNnRTBlbk1hdHlU
            Wm1IS0NSV0Z4K3lKY1lCQWx1OVZoK0V1ZXhnClJXcVNpckFNM3M4SlpmUTVwd1Vw
            eEdjNGExYXYvdU1wczF2TUtFZ0FjSG8KLS0tIFdkb1IyVVJwSjlMRUVkbnZEUit0
            SmJnazBNWE9rd3Vrd0R0WkM4Y1lHU1UK2B4vgfgyySNaX5fJyUVqs8u0wyI3q8Zs
            A2tzDQl+7hx4nMIe9M/bIBhYEk0mlVJXHWRJYWuSByPfoq5pEHUq4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRDNuR2UyTHNNaUNUc0NC
            T2xPSDVnY3MrZGdvWkNjQVNPeGFwZ2c1QlVnCmluRklSK1E3NHNmN2tNV0UwRjJO
            aU53RThXUlk4YXhXY29QaTc0Y0lieXcKLS0tIHlEK2s5NXNET2l5OE1Mb0x5aEd0
            c2VTWmtvendmdWo4QWdrWWlsbGEzK2MKzvLU2vtq47O04gW8SRWCUrRVD49imDrq
            Syeu/WGdODSV1f9lKtVmjoSYSpgJKZc2GtyJNevsWQ3NQxjg6+7Tag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreE5UVnNGRHVRVlBiSFp2
            NFdKTElQUS9KUW04cldDTjk5QUphS0dFMnprCjVKeWkyTzJWTnVkaG1GdmF3VVRN
            S0MzcEpmWTJpSy9uTVdMem1qOFkxYjAKLS0tIFY3MW1ETVFVWWlqRUV0SkRrVGNn
            UTV1WlpvM3VOajFUVnJwLzMydko5VFkKKc8vtLsW24PzE/bPXHaXJvdjqaCew4s3
            tiJoatT85eBHAtcMQDtw08sRgYF7O31uVPs0TfOP3+geBTpSy7Xnkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZW5SVnRGdThCNTdHZjZ5
            VjJjZ0ROeTAvMG1qWWllbFhzYXY3UVRkRkJrCmMrTDZNZnVkN2tPZU5tTmZEVUVF
            T0RPUUtXVDNxK3ZBUnB5WmZoVFZtVWsKLS0tIE1iQ0ZYM1VJRnBNVFI1QWNSUEFN
            eVBRZDkvTGoxeEZzK3R0YjVCNUxzY0kKGNJmK7vMYdIp34FgcnULPM2wZRj9ZO7d
            ztz1TF1RpPsqemfN996oJ6Qi3QGmBy32xhAF+JScs0oq//0i2WQfNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZUsxZTZ5YXhwRzl6TWQx
            SXlleTRNa3VEL3JhZ2dIWnN2T2FiSy9tamdBCjdFKzlwZ1MrUFB3eGhvZEc3Nlky
            YTdSUzhnTmV1NTBSNnpWNHhKb0FGYUUKLS0tIFJLWDJyZ2REaEV1MEJkcTBSVWt2
            NkRRVWNMR3QzbVRaSWhLZUtueHJmOUkKxMqo0fYeOpG7nBmAf2O/30hORrVAd7zc
            eQvY2TnhScXYHn6JGKYRtH1tywZnA1ViMcfTLx0lwY6CdyJX4Cw7dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T14:02:52Z"
    mac: ENC[AES256_GCM,data:1iJTviH+XH4T8jzwfbwmdHW297jqqJIAE9dsMlg86s0gTlKYZ4wfnXZeEYw+NRb2AKNuqFfePUxyfNkcv+HOHfCYo/jQbtJTQlce+y1UPb4bz8MLwYcv1ODIQbOZFEMz41Nxaoq/6vZ/J3srfZ5hsDTRM7pGddMV93uUIrKtcAs=,iv:098TyyAXycITAQC5fU5EhnuYnwSkYoA0WW70MzIXpV4=,tag:SwSvKWLmYAQw7/6R9cm7Aw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
