subjects: dict = {
    "anthropology": "Anthropology",
    "biology": "Biology",
    "business": "Business",
    "chemistry": "Chemistry",
    "cs": "Computer Science",
    "earth": "Earth Science",
    "economics": "Economics",
    "engineering": "Engineering",
    "geography": "Geography",
    "history": "History",
    "language": "Languages",
    "law": "Law",
    "literature": "Literature",
    "math": "Mathematics",
    "medicine": "Medicine",
    "philosophy": "Philosophy",
    "physics": "Physics",
    "political": "Political Science",
    "psychology": "Psychology",
    "sociology": "Sociology",
    "space": "Space Science",
    "arts": "Arts",
    "theology": "Theology",
}
