# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "chat_history.baml": "class MyUserMessage {\n  role \"user\" | \"assistant\"\n  content string\n}\n\nclass AgentAnswer {\n  answer string\n}\n\nfunction ChatWithLLM(messages: MyUserMessage[]) -> AgentAnswer {\n  client ClientLoadBalancer \n  prompt #\"\n    Answer the user's questions based on the chat history:\n    {% for message in messages %}\n      {{ _.role(message.role) }} \n      {{ message.content }}\n    {% endfor %}\n\n    Answer:\n    {{ ctx.output_format }}\n  \"#\n}\n\ntest TestName {\n  functions [ChatWithLLM]\n  args {\n    messages [\n      {\n        role \"user\"\n        content \"Hello! How are you? My name is Vaibhav.\"\n      }\n      {\n        role \"assistant\"\n        content \"Hi!\"\n      }\n    ]\n  }\n}\n\n",
    "clients.baml": "// Learn more about clients at https://docs.boundaryml.com/docs/snippets/clients/overview\n\n// Example Azure OpenAI client (uncomment to use)\nclient<llm> CustomAzureFrance {\n  provider azure-openai\n  options {\n    model env.LLM_MODEL_NAME\n    api_key env.AZURE_LLM_FRANCE_API_KEY\n    base_url env.AZURE_LLM_FRANCE_BASE_URL\n    api-version \"2024-05-01-preview\"\n  }\n}\n\nclient<llm> CustomAzureSweden {\n  provider azure-openai\n  options {\n    model env.LLM_MODEL_NAME\n    api_key env.AZURE_LLM_SWEDEN_API_KEY\n    base_url env.AZURE_LLM_SWEDEN_BASE_URL\n    api-version \"2024-05-01-preview\"\n  }\n}\n\n\nclient<llm> ClientLoadBalancer {\n  provider round-robin\n  options {\n    strategy [\n      CustomAzureFrance\n      CustomAzureSweden\n    ]\n  }\n}\n\n\nretry_policy Exponential {\n  max_retries 2\n  strategy {\n    type exponential_backoff\n    delay_ms 300\n    multiplier 1.5\n    max_delay_ms 10000\n  }\n}",
    "generators.baml": "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"go\", \"rust\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"python/pydantic\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.219.0\"\n\n    // Valid values: \"sync\", \"async\"\n    // This controls what `b.FunctionName()` will be (sync or async).\n    default_client_mode sync\n}\n",
    "resume.baml": "// Defining a data model.\nclass Resume {\n  name string\n  email string\n  experience string[]\n  competencies string[]\n}\n\n// Create a function to extract the resume from a string.\nfunction ExtractResume(resume: string) -> Resume {\n  client ClientLoadBalancer \n  prompt #\"\n    Extract from this content:\n    {{ resume }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n\n\n\n// Test the function with a sample resume. Open the VSCode playground to run this.\ntest vaibhav_resume {\n  functions [ExtractResume]\n  args {\n    resume #\"\n      Vaibhav Gupta\n      vbv@boundaryml.com\n\n      Experience:\n      - Founder at BoundaryML\n      - CV Engineer at Google\n      - CV Engineer at Microsoft\n\n      Skills:\n      - Rust\n      - C++\n    \"#\n  }\n}\n",
}

def get_baml_files():
    return _file_map